require('./integration/start')
require('./integration/test.001createUsers')
require('./integration/test.002sendMoney')
require('./integration/test.003invoices')
require('./integration/test.004cashin')
require('./integration/test.005cashout')
require('./integration/stop')
